### ISSUE TITLE
Errors with undefined scope variables.

### ISSUE THREAD

**Issue by crayfishx** [crayfishx/ansible-jerakia#2]
> User (GitHub handle unknown) Wrote by email:

One final question.

In the jerakia.yaml file used for Ansible under the scope section is there a mechanism to attempt relating multiple variables.
What we ended up having in our configuration file was:

```yaml
scope:
  hostname: ansible_nodename
  environment: ansible_local.custom.environment
  location: ansible_local.custom.location
  osfamily: ansible_os_family
```

What we found was that this ended up generating errors on systems that were missing local facts files that defined environment and location. Knowing this now we have adjusted the behavior of our playbooks but we were wondering if there was a supported mechanism to specifiy default values or other variables to use if one is not defined, i.e. something like the following:

```yaml
scope:
  hostname: ansible_nodename
  environment: ansible_local.custom.environment|default('development')
  location: ansible_local.custom.location|default('deploying')
  osfamily: ansible_os_family
```

Or

```yaml
scope:
  hostname: ansible_nodename
  environment: ansible_local.custom.environment, playbook_var_environment
  location: ansible_local.custom.location, playbook_var_location
  osfamily: ansible_os_family
```

**Comment by crayfishx** [comment]
This seems like a valid issue, I think we should address it.  I think the OP has the right idea but I'd like to see it done with native YAML rather than inventing a new syntax like `var|default('string')`

Maybe making the value of the scope keys more flexible by allowing a hash or a string.

So either of these would work, the second uses a default.

```yaml
# without default
scope:
  environment: ansible_local.custom.environment

# With default
scope:
  environment:
    var: ansible_local.custom.environment
    default: development
```

The above may be too complicated, I'm not sure, I've played around with the idea of an array because its shorter to express but how would we distinguish between a variable and a string?  eg:

```yaml
scope:
  environment: [ ansible_local.custom.environment, development ]
```

The above is shorter to express and assumes the first element of the array is a variable and the second is a hard coded string - this can be documented but is it obvious enough?

@beddari I think you're using this lookup plugin, any thoughts?
